al_quran/ui/urls.py
"""URLConf for al_quran.ui"""

from django.contrib.auth import views as auth
from django.urls import path

from al_quran.ui import views

# Create your patterns here.
app_name = "al-quran"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("chapters/", views.ChapterListView.as_view(), name="chapters"),
    path("chapters/<int:pk>/", views.ChapterDetailView.as_view(), name="chapter"),
    path("parts/", views.PartListView.as_view(), name="parts"),
    path("parts/<int:pk>/", views.PartDetailView.as_view(), name="part"),
    path("groups/", views.GroupListView.as_view(), name="groups"),
    path("groups/<int:pk>/", views.GroupDetailView.as_view(), name="group"),
    path("quarters/", views.QuarterListView.as_view(), name="quarters"),
    path("quarters/<int:pk>/", views.QuarterDetailView.as_view(), name="quarter"),
    path("pages/", views.PageListView.as_view(), name="pages"),
] + [
    path("accounts/login/", auth.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth.LogoutView.as_view(), name="logout"),
    path("accounts/signup/", views.SignupView.as_view(), name="signup"),
    path("accounts/profile/", views.ProfileView.as_view(), name="profile"),
    path(
        "accounts/<int:pk>/settings/",
        views.UserUpdateView.as_view(),
        name="update-user",
    ),
    path(
        "accounts/<int:pk>/delete/", views.UserDeleteView.as_view(), name="delete-user"
    ),
    path(
        "accounts/password/change/",
        auth.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password/change/done/",
        auth.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "accounts/password/reset/",
        auth.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "accounts/password/reset/done/",
        auth.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "accounts/password/reset/<uidb64>/<token>/",
        auth.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password/reset/complete/",
        auth.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

al_quran/ui/forms.py
"""Forms for al_quran.ui"""

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

# User model
User = get_user_model()


# Create your forms here.
class UserCreateForm(UserCreationForm):
    """Custom form for creating users"""

    class Meta(UserCreationForm.Meta):
        """Meta data"""

        model = User

al_quran/ui/views.py
"""Views for al_quran.ui"""

from typing import Any, Dict

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic
from django_filters.views import FilterView

from al_quran.core.chapters.models import Chapter
from al_quran.core.groups.models import Group
from al_quran.core.pages.models import Page
from al_quran.core.parts.models import Part
from al_quran.core.quarters.models import Quarter
from al_quran.ui import mixins
from al_quran.ui.forms import UserCreateForm

# User model
User = get_user_model()


# Create your views here.
class HomeView(generic.TemplateView):
    """Home page"""

    template_name = "ui/index.html"


class AboutView(generic.TemplateView):
    """About page"""

    template_name = "ui/about.html"


class ProfileView(LoginRequiredMixin, generic.TemplateView):
    """Profile page"""

    template_name = "registration/profile.html"


# User views
class SignupView(SuccessMessageMixin, generic.CreateView):
    """Creates a user"""

    model = User
    form_class = UserCreateForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("al-quran:profile")
    success_message = "Your account was created successfully!"


class UserUpdateView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    mixins.AccountOwnerMixin,
    generic.UpdateView,
):
    """Updates a user"""

    model = User
    template_name = "registration/edit.html"
    fields = ["font", "theme", "interpretation", "translation", "transliteration"]
    success_url = reverse_lazy("al-quran:profile")
    success_message = "Your settings was updated successfully!"


class UserDeleteView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    mixins.AccountOwnerMixin,
    generic.DeleteView,
):
    """Deletes a user"""

    model = User
    template_name = "registration/delete.html"
    success_url = reverse_lazy("al-quran:index")
    success_message = "Your account was deleted successfully!"


class ChapterListView(FilterView, generic.ListView):
    """Displays all Chapters"""

    model = Chapter
    ordering = "id"
    paginate_by = 25
    template_name = "ui/list/chapters.html"
    filterset_fields = ["id", "order", "type", "verse_count", "page_count"]


class BaseDetailView:
    """Base view that provides extra context to template"""

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        """Compute pages and add it to context"""

        reverse = f"al-quran:{self.model._meta.model_name.lower()}"

        return {
            **super().get_context_data(**kwargs),
            "prev_url": reverse_lazy(reverse, args=[self.object.id - 1]),
            "next_url": reverse_lazy(reverse, args=[self.object.id + 1]),
        }


class ChapterDetailView(BaseDetailView, generic.DetailView):
    """Displays a Chapter"""

    model = Chapter
    template_name = "ui/detail/chapter.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        """Compute pages and add it to context"""

        return {
            **super().get_context_data(**kwargs),
            "pages": Page.objects.filter(verses__chapter_id=self.object.id)
            .distinct()
            .prefetch_related("verses"),
        }


class PartListView(FilterView, generic.ListView):
    """Displays all Parts"""

    model = Part
    ordering = "id"
    paginate_by = 15
    template_name = "ui/list/parts.html"
    filterset_fields = ["id", "verse_count", "page_count"]


class PartDetailView(BaseDetailView, generic.DetailView):
    """Displays a Part"""

    model = Part
    template_name = "ui/detail/part.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        """Compute pages and add it to context"""

        return {
            **super().get_context_data(**kwargs),
            "pages": Page.objects.filter(verses__part_id=self.object.id)
            .distinct()
            .prefetch_related("verses"),
        }


class GroupListView(FilterView, generic.ListView):
    """Displays all Groups"""

    model = Group
    ordering = "id"
    paginate_by = 30
    template_name = "ui/list/groups.html"
    filterset_fields = ["id", "part", "verse_count", "page_count"]


class GroupDetailView(BaseDetailView, generic.DetailView):
    """Displays a Group"""

    model = Group
    template_name = "ui/detail/group.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        """Compute pages and add it to context"""

        return {
            **super().get_context_data(**kwargs),
            "pages": Page.objects.filter(verses__group_id=self.object.id)
            .distinct()
            .prefetch_related("verses"),
        }


class QuarterListView(FilterView, generic.ListView):
    """Displays all Quarters"""

    model = Quarter
    ordering = "id"
    paginate_by = 60
    template_name = "ui/list/quarters.html"
    filterset_fields = ["id", "part", "group", "verse_count", "page_count"]


class QuarterDetailView(BaseDetailView, generic.DetailView):
    """Displays a Quarter"""

    model = Quarter
    template_name = "ui/detail/quarter.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        """Compute pages and add it to context"""

        return {
            **super().get_context_data(**kwargs),
            "pages": Page.objects.filter(verses__quarter_id=self.object.id)
            .distinct()
            .prefetch_related("verses"),
        }


class PageListView(FilterView, generic.ListView):
    """Displays all Pages"""

    model = Page
    ordering = "id"
    paginate_by = 100
    template_name = "ui/list/pages.html"
    filterset_fields = ["id", "chapter", "part", "group", "quarter", "verse_count"]

al_quran/ui/templates/ui/components/page.html
{% load i18n %}

<div class="carousel-item size-full lg:w-1/2">
  <section
    id="page-{{ page.id }}"
    class="relative card ring-1 ring-base-300 rounded-box"
  >
    <header
      class="absolute inset-x-0 top-0 z-10 backdrop-blur-3xl flex items-center justify-between gap-2 p-4 rounded-t-box"
    >
      <div
        class="tooltip tooltip-bottom tooltip-primary"
        data-tip="{% trans 'Read' %}"
      >
        <a
          href="{% url 'al-quran:chapter' page.chapter_id %}"
          class="badge badge-xs badge-soft badge-primary lg:badge-md"
        >
          سُورَةُ {{ page.chapter }}
        </a>
      </div>

      <div
        class="tooltip tooltip-bottom tooltip-primary"
        data-tip="{% trans 'Read' %}"
      >
        <a
          href="{% url 'al-quran:part' page.part_id %}"
          class="badge badge-xs badge-soft badge-primary lg:badge-md"
        >
          {% trans 'Part' %} {{ page.part_id }}
        </a>
      </div>
    </header>

    <main class="card-body px-4 grow py-20 overflow-y-auto lg:px-6">
      <div role="text" class="text-center">
        {% for verse in page.verses.all %}
        <!---->
        {% if verse.number == 1 %}
        <div
          class="card card-body flex-row items-center justify-between rounded-box bg-base-200 shadow-sm my-4"
        >
          <div
            class="tooltip tooltip-bottom tooltip-success"
            data-tip="{% trans 'Order' %}"
          >
            <span class="badge badge-xs badge-success lg:badge-md">
              <span>تَرْتِيبُهَا</span>
              {{ verse.chapter.id }}
            </span>
          </div>

          <h1 class="text-lg font-bold text-primary text-shadow-lg lg:text-2xl">
            سُورَةُ {{ verse.chapter }}
          </h1>

          <div
            class="tooltip tooltip-bottom tooltip-success"
            data-tip="{% trans 'Verse count' %}"
          >
            <span class="badge badge-xs badge-success lg:badge-md">
              <span>آيَاتُهَا</span>
              {{ verse.chapter.verse_count }}
            </span>
          </div>
        </div>

        <span class="block mb-4 text-primary text-base/8 lg:text-2xl/12">
          {{ verse.content|slice:'0:39' }}
        </span>

        <span
          id="verse-{{ verse.chapter_id }}:{{ verse.number }}"
          class="text-base/8 lg:text-2xl/12"
        >
          {{ verse.content|slice:'39:' }}
        </span>

        {% else %}
        <span
          id="verse-{{ verse.chapter_id }}:{{ verse.number }}"
          class="text-base/8 lg:text-2xl/12"
        >
          {{ verse.content }}
        </span>
        {% endif %}

        <div
          class="tooltip tooltip-bottom tooltip-primary"
          data-tip="{% trans 'Options' %}"
        >
          <button
            onclick="options{{ verse.chapter_id }}_{{ verse.number }}.showModal()"
            class="btn btn-xs btn-square btn-primary md:btn-sm"
          >
            {{ verse.number }}
            <span class="sr-only">{% trans 'Options' %}</span>
          </button>
        </div>

        <dialog
          id="options{{ verse.chapter_id }}_{{ verse.number }}"
          class="modal font-sans rtl:font-kufi"
        >
          <section class="relative modal-box grid max-w-xl gap-6 bg-base-100">
            <header
              class="flex items-center justify-between gap-4 text-primary"
            >
              <h1 class="text-lg font-semibold lg:text-2xl">
                {% trans 'Verse' %} {{ verse.chapter_id }}:{{ verse.number }}
              </h1>

              <div
                class="tooltip tooltip-left rtl:tooltip-right tooltip-error"
                data-tip="{% trans 'Close' %}"
              >
                <button
                  onclick="options{{ verse.chapter_id }}_{{ verse.number }}.close()"
                  class="btn btn-square btn-soft btn-primary hover:btn-error"
                >
                  <i data-lucide="x" class="size-4 lg:size-6"></i>
                  <span class="sr-only">{% trans 'Close' %}</span>
                </button>
              </div>
            </header>

            <main class="grid gap-4 lg:gap-6">
              <menu class="grid gap-2">
                {% if request.user.is_authenticated %}
                <form
                  method="post"
                  action="/api/verses/{{ verse.id }}/bookmark?redirect=1"
                >
                  {% csrf_token %}
                  <button
                    type="submit"
                    class="btn copy btn-ghost btn-sm justify-start gap-4 w-full lg:btn-md"
                  >
                    <i data-lucide="bookmark-plus" class="size-4 lg:size-6"></i>
                    <span>{% trans 'Bookmark' %}</span>
                  </button>
                </form>
                {% endif %}

                <button
                  data-clipboard-text="({{ verse.content }}), {% trans 'Chapter' %} {{ verse.chapter_id }} {% trans 'Verse' %} {{ verse.id }}"
                  class="btn copy btn-ghost btn-sm justify-start gap-4 lg:btn-md"
                >
                  <i data-lucide="copy" class="size-4 lg:size-6"></i>
                  <span>{% trans 'Copy verse' %}</span>
                </button>

                <button
                  data-clipboard-text="{{ request.build_absolute_uri }}#verse-{{ verse.chapter_id }}:{{ verse.number }}"
                  class="btn copy btn-ghost btn-sm justify-start gap-4 lg:btn-md"
                >
                  <i data-lucide="link" class="size-4 lg:size-6"></i>
                  <span>{% trans 'Copy link' %}</span>
                </button>
              </menu>
            </main>

            <footer class="-mx-5 -mb-5 grid">
              <button
                onclick="options{{ verse.chapter_id }}_{{ verse.number }}.close()"
                class="btn rounded-b-box rounded-tr btn-primary"
              >
                {% trans 'Close' %}
              </button>
            </footer>
          </section>
        </dialog>
        {% endfor %}
      </div>
    </main>

    <footer
      class="absolute inset-x-0 bottom-0 z-10 backdrop-blur-3xl flex items-center justify-between gap-2 p-4 rounded-b-box"
    >
      <div
        class="tooltip tooltip-top tooltip-primary"
        data-tip="{% trans 'Read' %}"
      >
        <a
          href="{% url 'al-quran:group' page.group_id %}"
          class="badge badge-xs badge-soft badge-primary lg:badge-md"
        >
          {% trans 'Group' %} {{ page.group_id }}
        </a>
      </div>

      <div
        class="tooltip tooltip-top tooltip-primary"
        data-tip="{% trans 'Page' %}"
      >
        <span class="badge badge-xs badge-primary lg:badge-lg">
          {{ page.id }}
        </span>
      </div>

      <div
        class="tooltip tooltip-top tooltip-primary"
        data-tip="{% trans 'Read' %}"
      >
        <a
          href="{% url 'al-quran:quarter' page.quarter_id %}"
          class="badge badge-xs badge-soft badge-primary lg:badge-md"
        >
          {% trans 'Quarter' %} {{ page.quarter_id }}
        </a>
      </div>
    </footer>
  </section>
</div>

al_quran/ui/templates/ui/detail/chapter.html
{% extends 'ui/detail/base.html' %}{% load i18n %}

<!---->
{% block title %}{{ block.super }} | {{ chapter.name }}{% endblock %}

al_quran/ui/templates/ui/index.html
{% extends 'ui/base.html' %}{% load i18n %}

<!---->
{% block content %}
<section id="hero">
  <div class="hero">
    <div class="hero-content py-40">
      <div class="max-w-xl">
        <h1 class="text-3xl lg:text-5xl font-black">
          {% trans 'Experience the Quran Like Never Before' %}
        </h1>

        <p class="py-6 text-xl">
          {% blocktrans trimmed %}An interactive journey to deepen your
          understanding and connection{% endblocktrans %}
        </p>

        <a
          href="{% url 'al-quran:chapters' %}"
          class="btn btn-lg btn-primary font-bold"
        >
          {% trans 'Begin Your Journey' %}
        </a>
      </div>
    </div>
  </div>
</section>

<section id="features" class="grid gap-4 lg:gap-8">
  <h1 class="text-5xl font-bold">{% trans 'Features' %}</h1>

  <div class="grid grid-cols-12 gap-4">
    <div class="col-span-12 lg:col-span-8">
      <figure class="diff aspect-16/9 rounded-box" tabindex="0">
        <div class="diff-item-1" role="img" tabindex="0">
          <img
            src="https://github.com/user-attachments/assets/cf7e63c8-72db-463b-8c98-f7ba3221b707"
            alt="{% trans 'Al Quran Screenshot' %}"
          />
        </div>
        <div class="diff-item-2" role="img">
          <img
            src="https://github.com/user-attachments/assets/ca45ba64-2cb7-40db-942a-362c046b7b47"
            alt="{% trans 'Al Quran Screenshot' %}"
          />
        </div>
        <div class="diff-resizer"></div>
      </figure>
    </div>
    <div class="col-span-12 lg:col-span-4">
      <div
        class="hero bg-primary py-24 text-primary-content h-full rounded-box"
      >
        <div class="hero-content text-center">
          <div class="max-w-lg">
            <h1 class="text-2xl lg:text-4xl font-bold">
              {% trans 'Interactive Reading Experience' %}
            </h1>

            <p class="py-6">
              {% blocktrans trimmed %}Personalized themes and font adjustments
              create a comfortable reading environment.{% endblocktrans %}
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-span-12 lg:col-span-4">
      <div
        class="flex items-center justify-center size-full p-12 bg-base-200 rounded-box"
      >
        <i data-lucide="audio-lines" class="size-1/2"></i>
      </div>
    </div>
    <div class="col-span-12 lg:col-span-8">
      <div
        class="hero bg-secondary py-24 h-full text-secondary-content rounded-box"
      >
        <div class="hero-content text-center">
          <div class="max-w-lg">
            <h1 class="text-2xl lg:text-4xl font-bold">
              {% trans 'Audio Recitations' %}
            </h1>

            <p class="py-6">
              {% blocktrans trimmed %}Enjoy beautiful recitations by renowned
              Qaris.{% endblocktrans %}
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-span-12 lg:col-span-8">
      <div class="hero bg-accent h-full py-24 text-accent-content rounded-box">
        <div class="hero-content text-center">
          <div class="max-w-lg">
            <h1 class="text-2xl lg:text-4xl font-bold">
              {% trans 'Advanced Search & Bookmarking' %}
            </h1>

            <p class="py-6">
              {% blocktrans trimmed %}Quickly locate your favorite verses and
              track progress.{% endblocktrans %}
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-span-12 lg:col-span-4">
      <div
        class="flex items-center justify-center size-full p-12 bg-base-200 rounded-box"
      >
        <i data-lucide="bookmark" class="size-1/2"></i>
      </div>
    </div>

    <div class="col-span-12 lg:col-span-4">
      <div
        class="flex items-center justify-center size-full p-12 bg-base-200 rounded-box"
      >
        <i data-lucide="languages" class="size-1/2"></i>
      </div>
    </div>
    <div class="col-span-12 lg:col-span-8">
      <div
        class="hero bg-warning h-full py-24 text-warning-content rounded-box"
      >
        <div class="hero-content text-center">
          <div class="max-w-lg">
            <h1 class="text-2xl lg:text-4xl font-bold">
              {% trans 'Multi-Language & Tafsir Support' %}
            </h1>

            <p class="py-6">
              {% blocktrans trimmed %}Access translations and scholarly
              commentary in several languages.{% endblocktrans %}
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-span-12 lg:col-span-8">
      <div class="mockup-browser border border-primary w-full">
        <div class="mockup-browser-toolbar">
          <div class="input input-primary bg-transparent">
            https://al-quran.com
          </div>
        </div>
        <div class="grid place-content-center">
          <img
            alt="{% trans 'Al Quran' %}"
            src="https://github.com/user-attachments/assets/ca45ba64-2cb7-40db-942a-362c046b7b47"
          />
        </div>
      </div>
    </div>
    <div class="col-span-12 lg:col-span-4">
      <div class="hero bg-info py-24 text-info-content h-full rounded-box">
        <div class="hero-content text-center">
          <div class="max-w-lg">
            <h1 class="text-2xl lg:text-4xl font-bold">{% trans 'Modern' %}</h1>

            <p class="py-6">
              {% blocktrans trimmed %}Our Quran app is crafted with cutting-edge
              technology to provide a seamless, engaging, and personalized
              experience.{% endblocktrans %}
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-span-12 flex lg:col-span-4">
      <div class="mockup-phone border-primary mx-auto">
        <div class="mockup-phone-display">
          <img
            alt="{% trans 'Al Quran' %}"
            src="https://github.com/user-attachments/assets/c5f3b891-104a-4de7-a470-40365e0412ad"
          />
        </div>
      </div>
    </div>
    <div class="col-span-12 lg:col-span-8">
      <div class="hero bg-error py-24 h-full text-error-content rounded-box">
        <div class="hero-content text-center">
          <div class="max-w-lg">
            <h1 class="text-2xl lg:text-4xl font-bold">
              {% trans 'Designed for Every User, Everywhere' %}
            </h1>

            <p class="py-6">
              {% blocktrans trimmed %}Whether you're browsing on a desktop,
              tablet, or mobile device, our platform adapts effortlessly to your
              needs.{% endblocktrans %}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="join">
  <div class="hero">
    <div class="hero-content py-40">
      <div class="max-w-2xl">
        <h1 class="text-3xl lg:text-5xl font-black">
          {% trans 'Join Us & Earn Hasanat' %}
        </h1>

        <p class="py-6 text-xl">
          {% blocktrans trimmed %}The Quran has always been a guiding light,
          offering wisdom, peace, and spiritual fulfillment.{% endblocktrans %}
        </p>

        <a
          href="{% url 'al-quran:chapters' %}"
          class="btn btn-lg btn-primary font-bold"
        >
          {% trans 'Start Earning Hasanat' %}
        </a>
      </div>
    </div>
  </div>
</section>
{% endblock %}

al_quran/ui/templates/ui/list/chapters.html
{% extends 'ui/list/base.html' %}{% load i18n %}

<!---->
{% block title %}{{ block.super }} | {% trans 'Chapters' %}{% endblock %}

<!---->
{% block heading %}{% trans 'Chapters' %}{% endblock %}

<!---->
{% block main %}
<!---->
{% for chapter in chapter_list.all %}
<li id="item-{{ chapter.id }}" class="col-span-12 md:col-span-6 lg:col-span-4">
  <div
    class="card shadow-sm size-full rounded-box card-sm overflow-hidden hover:bg-base-200 hover:shadow-xl md:card-md lg:card-lg xl:card-xl"
  >
    <span
      class="badge badge-soft badge-primary rounded-xs lg:badge-lg xl:badge-xl"
    >
      {% trans 'Chapter' %} {{ chapter.id }}
    </span>

    <div class="card-body gap-4 lg:gap-6">
      <h2 class="card-title text-primary">سُورَةُ {{ chapter.name }}</h2>

      <ul class="grid gap-2 grid-cols-2">
        <li class="tooltip tooltip-top" data-tip="{% trans 'Type' %}">
          <a
            href="{% url 'al-quran:chapters' %}?type={{ chapter.type }}"
            class="flex items-center gap-2 lg:gap-4"
          >
            <i data-lucide="map-pin" class="size-4 lg:size-6"></i>
            {% if chapter.type %}{% trans 'Meccan' %}
            <!---->
            {% else %}{% trans 'Medinan' %}{% endif %}
          </a>
        </li>
        <li class="tooltip tooltip-top" data-tip="{% trans 'Order' %}">
          <span class="flex items-center gap-2 lg:gap-4">
            <i data-lucide="arrow-down-0-1" class="size-4 lg:size-6"></i>
            {% trans 'Order' %} {{ chapter.order }}
          </span>
        </li>
        <li class="tooltip tooltip-top" data-tip="{% trans 'pages' %}">
          <span class="flex items-center gap-2 lg:gap-4">
            <i data-lucide="book-open" class="size-4 lg:size-6"></i>
            {{ chapter.page_count }} {% trans 'pages' %}
          </span>
        </li>
        <li class="tooltip tooltip-top" data-tip="{% trans 'verses' %}">
          <span class="flex items-center gap-2 lg:gap-4">
            <i data-lucide="book-text" class="size-4 lg:size-6"></i>
            {{ chapter.verse_count }} {% trans 'verses' %}
          </span>
        </li>
      </ul>

      <a
        href="{% url 'al-quran:chapter' chapter.id %}"
        class="btn btn-primary lg:btn-lg"
      >
        {% trans 'Read' %}
        <i
          data-lucide="chevron-right"
          class="size-4 lg:size-6 rtl:rotate-180"
        ></i>
      </a>
    </div>
  </div>
</li>
{% endfor %}
<!---->
{% endblock %}

al_quran/ui/templates/ui/list/groups.html
{% extends 'ui/list/base.html' %}{% load i18n %}

<!---->
{% block title %}{{ block.super }} | {% trans 'Groups' %}{% endblock %}

<!---->
{% block heading %}{% trans 'Groups' %}{% endblock %}

<!---->
{% block main %}
<!---->
{% for group in group_list.all %}
<li id="item-{{ group.id }}" class="col-span-12 md:col-span-6 lg:col-span-4">
  <div
    class="card shadow-sm size-full rounded-box card-sm overflow-hidden hover:bg-base-200 hover:shadow-xl md:card-md lg:card-lg xl:card-xl"
  >
    <span
      class="badge badge-soft badge-primary rounded-xs lg:badge-lg xl:badge-xl"
    >
      {% trans 'Group' %} {{ group.id }}
    </span>

    <div class="card-body gap-4 lg:gap-6">
      <h2 class="card-title text-primary">
        {% trans 'Group' %} {{ group.id }}
      </h2>

      <ul class="grid gap-2 grid-cols-2">
        <li class="tooltip tooltip-top" data-tip="{% trans 'Part' %}">
          <span class="flex items-center gap-2 lg:gap-4">
            <i data-lucide="component" class="size-4 lg:size-6"></i>
            {% trans 'Part' %} {{ group.part_id }}
          </span>
        </li>
        <li class="tooltip tooltip-top" data-tip="{% trans 'pages' %}">
          <span class="flex items-center gap-2 lg:gap-4">
            <i data-lucide="book-open" class="size-4 lg:size-6"></i>
            {{ group.page_count }} {% trans 'pages' %}
          </span>
        </li>
        <li class="tooltip tooltip-top" data-tip="{% trans 'verses' %}">
          <span class="flex items-center gap-2 lg:gap-4">
            <i data-lucide="book-text" class="size-4 lg:size-6"></i>
            {{ group.verse_count }} {% trans 'verses' %}
          </span>
        </li>
      </ul>

      <a
        href="{% url 'al-quran:group' group.id %}"
        class="btn btn-primary lg:btn-lg"
      >
        {% trans 'Read' %}
        <i
          data-lucide="chevron-right"
          class="size-4 lg:size-6 rtl:rotate-180"
        ></i>
      </a>
    </div>
  </div>
</li>
{% endfor %}
<!---->
{% endblock %}